    </div>
    <div class="more-button">
        <a id="viewMore" target="blank" href=""><?php echo $this->__('Show more testimonials') ?></a>
    </div>
</div>
<script type="text/javascript">
//<![CDATA[
    var testimonials = new Testimonials("<?php echo $this->getUrl('testimonials/index/index') ?>",
                                        '.testimonials');
    $('viewMore').observe('click', testimonials.makeAjaxCall.bind(testimonials));
    <?php $_testimonials = $this->getTestimonials(); ?>
    <?php if ($this->getPerPage() >= $_testimonials->getSize()): ?>
    $('viewMore').hide();
    <?php endif ?>
//]]>
</script>