    <?php
        if (!$this->getIsAjax()) {
            echo $this->getChildHtml('testimonials.list.title');
        }
        $_testimonials = $this->getTestimonials();
        $_width = Mage::helper('testimonials')->getImageWidth();
        $_height = Mage::helper('testimonials')->getImageHeight();
    ?>
    <?php if($_testimonials->getSize()): ?>
        <?php foreach ($_testimonials as $_testimonial): ?>
            <?php Mage::helper('testimonials')->escapeTetimonial($_testimonial); ?>
            <div class="testimonial">
                <?php if ($image = $this->getImagePath($_testimonial)): ?>
                <div class="testimonial-image" style="width: <?php echo ($_width + 10) ?>px">
                    <img src="<?php echo $this->helper('testimonials/image')->
                    init($image)->resize($_width, $_height); ?>"
                    alt="Profile image" />
                </div>
                <?php endif ?>
                <div class="container" style="width: auto; margin-left: <?php echo $image ? ($_width + 10) : 0 ?>px">
                    <div class="content-wrapper">
                        <div class="message-wrapper">
                            <div class="message"><?php echo $_testimonial->getMessage() ?>
                                <span class="author-info">
                                    <?php echo $_testimonial->getName();
                                        if ($_testimonial->getCompany() &&
                                            Mage::helper('testimonials')->isCompanyEnabled()): ?>,
                                        <?php if ($_testimonial->getWebsite() &&
                                                  Mage::helper('testimonials')->isWebsiteEnabled()): ?>
                                            <a href="<?php echo $_testimonial->getWebsite() ?>">
                                            <?php echo $_testimonial->getCompany(); ?></a><?php
                                            else:
                                                echo $_testimonial->getCompany();
                                            endif;
                                        endif; ?>
                                        <?php if (Mage::helper('testimonials')->showUserEmail()):
                                            echo ', ' . $_testimonial->getEmail();
                                        endif ?>
                                </span>
                                <?php if ($this->canShowSocial($_testimonial)): ?>
                                <div class="socialInfo">
                                    <?php echo Mage::helper('testimonials')->__('Find us on'); ?>
                                    <?php if ($_testimonial->getFacebook() &&
                                              Mage::helper('testimonials')->isFacebookEnabled()): ?>
                                        <a href="<?php echo $_testimonial->getFacebook() ?>">
                                        <img src="<?php echo Mage::helper('testimonials')->getFacebookIcon() ?>" /><?php echo Mage::helper('testimonials')->__('Facebook') ?></a>
                                    <?php endif ?>
                                    <?php if ($_testimonial->getTwitter() &&
                                              Mage::helper('testimonials')->isTwitterEnabled()): ?>
                                    , <a href="<?php echo $_testimonial->getTwitter() ?>">
                                    <img src="<?php echo Mage::helper('testimonials')->getTwitterIcon() ?>" /><?php echo Mage::helper('testimonials')->__('Twitter') ?></a><?php endif ?>
                                </div>
                                <?php endif ?>
                            </div>
                        </div>
                        <div style="margin: 10px 0 0 <?php echo $image ? 40 : 80 ?>px">
                            <div class="rating-wrapper ratings-table">
                                <?php if ($_testimonial->getRating()): ?>
                                <div class="rating-title"><?php echo $this->__('Rating') ?></div>
                                <div class="rating-box"><div class="rating" style="width: <?php echo $_testimonial->getRating() / 5 * 100 ?>%;"></div></div>
                                <?php endif ?>
                            </div>
                            <div class="testimonial-date">
                                <span><?php echo $this->__('Placed on') ?></span>
                                <span class="nobr"><?php echo $this->formatDate($_testimonial->getDate(), 'long') ?></span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        <?php endforeach; ?>
    <?php else: ?>
        <p><?php echo $this->__('No testimonials found.'); ?></p>
    <?php endif ?>
    <?php
        if (!$this->getIsAjax()):
            echo $this->getChildHtml('testimonials.list.bottom');
        endif
    ?>
    <?php if ($_testimonials->getCurPage() * $_testimonials->getPageSize() >= $_testimonials->getSize()): ?>
        <script type="text/javascript">
        //<![CDATA[
            if ($('testimonials-view-more-button')) {
                $('testimonials-view-more-button').hide();
            }
        //]]>
        </script>
    <?php endif ?>
