    <?php 
        if (!$this->getIsAjax()) {
            echo $this->getChildHtml('testimonials.list.title'); 
        }
        $_testimonials = $this->getTestimonials(); 
        $_width = Mage::helper('testimonials')->getImageWidth();
        $_height = Mage::helper('testimonials')->getImageHeight();
    ?>
    <?php if($_testimonials->getSize()): ?>
        <?php foreach ($_testimonials as $_testimonial): ?>
            <div class="testimonial">
                <span class="bqstart">&#8220;</span>
                <?php if ($image = $this->getImagePath($_testimonial)): ?>
                <div class="testimonial-image" style="width: <?php echo ($_width + 10) ?>px">
                    <img src="<?php echo $this->helper('testimonials/image')->
                    init($image)->resize($_width, $_height); ?>" 
                    alt="Profile image" />
                </div>
                <?php endif ?>
                <div style="width: auto; margin-left: <?php echo $image ? ($_width + 10) : 0 ?>px">
                    <div class="content-wrapper">
                        <div class="top-info" style="margin-left: <?php echo $image ? 0 : 40 ?>px">
                            <div class="rating-wrapper">
                                <?php if ($_testimonial->getRating()): ?>
                                <div class="rating-title"><?php echo $this->__('Rating') ?></div>
                                <div class="rating-box"><div class="rating" style="width: <?php echo $_testimonial->getRating() / 5 * 100 ?>%;"></div></div>
                                <?php endif ?>
                            </div>
                            <div class="testimonial-date">
                                <span><?php echo $this->__('Placed on') ?></span>
                                <span class="nobr"><?php echo $this->formatDate($_testimonial->getDate(), 'long') ?></span>
                            </div>
                        </div>
                        <div class="message-wrapper">
                            <div class="message"><?php echo $_testimonial->getMessage() ?></div>
                            <div class="author-info"><?php echo $this->getAuthorInfoHtml($_testimonial); ?></div>
                            <?php $socialHtml = $this->getSocialInfoHtml($_testimonial); ?>
                            <?php if ($socialHtml): ?>
                            <div class="socialInfo"><?php echo $socialHtml; ?></div>
                            <?php endif ?>
                        </div>
                    </div>
                </div>
                <span class="bqend">&#8221;</span>
            </div>
            <div class="clearer"></div>
        <?php endforeach; ?>
    <?php else: ?>
        <p><?php echo $this->__('No testimonials found.'); ?></p>
    <?php endif ?>
    <?php if ($_testimonials->getCurPage() * $_testimonials->getPageSize() >= $_testimonials->getSize()): ?>
        <script type="text/javascript">
        //<![CDATA[
            if ($('viewMore')) $('viewMore').hide();
        //]]>
        </script>
    <?php endif ?>
    <?php 
        if (!$this->getIsAjax()):
            echo $this->getChildHtml('testimonials.list.bottom'); 
        endif 
    ?>