<div class="testimonials-list">
    <?php if (is_null($this->getShowTitle()) || $this->getShowTitle()): ?>
        <div class="page-title">
            <h1><?php echo $this->__('Testimonials') ?></h1>
            <div class="submit-testimonial">
                <button class="button" onclick="setLocation('<?php echo $this->getUrl('testimonials/index/new'); ?>')">
                    <span><span><?php echo $this->__('Submit Your Testimonial') ?></span></span>
                </button>
            </div>
        </div>
    <?php endif ?>
    <div class="testimonials" data-ajax-url="<?php echo $this->getUrl('testimonials/index/index') ?>">
