<div class="testimonials-list">
    <div class="page-title">
        <h1><?php echo $this->__('Testimonials') ?></h1>
        <div class="submit-testimonial">
            <button class="button" onclick="setLocation('<?php echo $this->getUrl('testimonials/index/new'); ?>')">
                <span><span>Submit Your Testimonial</span></span>
            </button>
        </div>
    </div>
    <div class="testimonials">