<?php $testimonial = $this->getTestimonial(); ?>
<div class="block block-testimonials">
    <div class="block-title">
        <strong><span><?php echo $this->__('Testimonials') ?></span></strong>
    </div>
    <div class="block-content">
        <div class="content">
            <?php if ($testimonial->getRating()): ?>
                <div class="rating-title"><?php echo $this->__('Rating: ') ?></div>
                <div class="rating-box"><div class="rating" style="width: <?php echo $testimonial->getRating() / 5 * 100 ?>%;"></div></div>
            <?php endif ?>
            <div class="message"><?php echo $testimonial->getMessage(); ?></div>
            <div class="name"><?php echo $testimonial->getName(); ?></div>
        </div>
        <div class="actions">
            <a href="<?php echo $this->getUrl('testimonials/index') ?>"><?php echo $this->__('View all testimonials') ?></a>
        </div>
    </div>
</div>